name: iSteam
options:
  bundleIdPrefix: com.chantinlongx
  xcodeVersion: "26.0"
  deploymentTarget:
    iOS: "16.0"
settings:
  base:
    SWIFT_VERSION: "5.9"
    IPHONEOS_DEPLOYMENT_TARGET: "16.0"
    ARCHS: "arm64 arm64e"
    EXCLUDED_ARCHS[sdk=iphonesimulator*]: "arm64e"
targets:
  iSteam:
    type: application
    platform: iOS
    sources:
      - path: iSteam
    settings:
      base:
        PRODUCT_BUNDLE_IDENTIFIER: com.chantinlongx.iSteam
        INFOPLIST_FILE: iSteam/Info.plist
        CODE_SIGN_ENTITLEMENTS: iSteam/iSteam.entitlements
        SWIFT_OBJC_BRIDGING_HEADER: iSteam/iSteam-Bridging-Header.h
        OTHER_LDFLAGS:
          - "$(inherited)"
          - "-ObjC"
